version: "1"
services:
  videoapp:
    image: mksrt/cars-app:controller
    container_name: controller
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/CarsContentDB?createIfNotExists=true?useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update
        #-H2 data
        #- spring.jpa.show-sql=true
        #- spring.h2.console.enabled=true
        #- spring.datasource.url=jdbc:h2:file:A:/path/carsRentData
        #- spring.jpa.hibernate.ddl-auto=update
        #- spring.datasource.generate-unique-name=false
        #- spring.datasource.username=someUser
        #- spring.datasource.password=Password
      #- spring.datasource.url=jdbc:mysql://db:3306/VideoContentDataBase?createIfNotExists=true?useSSL=false
    depends_on:
      - db
      - front
    ports:
      - "8080:8080"
    restart: always
  db:
    image: mysql
    container_name: cars_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=CarsContentDB
    ports:
      - "3306:3306"
    restart: always
  front:
    image: mksrt/cars-app:front
    container_name: front
    ports:
      - "8081:8081"
